Task 1:
1.
Write a function to compute 5/0 and use try/except to catch the exceptions.




In [1]:
def func():
    try:
        a = 5/0
    except Exception as e:
        print(e)
        
func()        
        
   

division by zero


2.
Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
Output should come as below:
Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.

In [14]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for i in subjects:
        for j in verbs:
            for k in objects:
                print(i,j,k,".")
                

Americans  play Baseball .
Americans  play Cricket .
Americans  watch Baseball .
Americans  watch Cricket .
Indians play Baseball .
Indians play Cricket .
Indians watch Baseball .
Indians watch Cricket .


Task 2:
1.
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [9]:
import numpy as np
def alex_matrix(lst,N):
    print(np.column_stack( [lst**(N-i-1) for i in range(N)]))              
a = np.array([1,2,3,4,5])                    
alex_matrix(a,4)

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]
